export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  LIBRARY: '/library',
  UPLOAD: '/upload',
  BOOK_DETAILS: '/books/:id',
  READER: '/reader/:id',
  FAVORITES: '/favorites',
  COLLECTIONS: '/collections',
  NOTES: '/notes',
  READING: '/reading',
  ANALYTICS: '/analytics',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  STORAGE: '/storage',
  DESIGN_SYSTEM: '/design-system',
  FORGOT_PASSWORD: '/forgot-password',
  FLASHCARDS: '/flashcards',
} as const
